Rg/db elasticpool feature
tidalmigrations/gists pull request #18
Opened 2023-09-20 21:52 UTC by gkiranreddy

- Sync dbs - elastic pool and associated db sync feature
- Custom fields 
- Sync Servers - app service feature with custom fields

2023-10-06 01:59 UTC, dcolebatch requested changes
Hi @gkiranreddy - please take a look at this feedback

2023-10-11 22:09 UTC, gkiranreddy commented on azure_dbs.rb
> +    # file_path = "#{Dir.pwd}/tidal_#{type}_data.json"
I will make this change

2023-10-12 15:50 UTC, gkiranreddy reviewed
- I updated code based on the review, 
- And also added batching feature for VMs script, Currently I set the SAVE_INTERNAL to 10 just to test. But this can be updated to what ever we see fit

2023-10-12 21:26 UTC, dcolebatch commented
Thanks @gkiranreddy!

1) Just confirming: you ran this and it worked ok?  Particularly the custom fields changes, did they come through as you expected?

2) with respect to the periodic saving to file- I believe the intent here was to be able to handle very large environments without running out of memory, or causing 500s on the Tidal API?

 I have two observations:
a) We appear to write to file, but also maintain the data in a global variable? (So, our memory footprint might actually be worse now)
b) we delete the file at the end, which would prevent us from being able to re-play the data to `tidal sync...` manually when troubleshooting.

I wonder if we might consider periodically writing to file *and* syncing to tidal tools if some flag is set?

e.g. the below, with no STDOUT writing of JSON:
```./azure_vms.rb -sync-page 10```

as an addiotional option to the existing `./azure_vms.rb | tidal sync ` workflow

2023-10-12 21:26 UTC, dcolebatch commented
Thanks @gkiranreddy!

1) Just confirming: you ran this and it worked ok?  Particularly the custom fields changes, did they come through as you expected?

2) with respect to the periodic saving to file- I believe the intent here was to be able to handle very large environments without running out of memory, or causing 500s on the Tidal API?

 I have two observations:
a) We appear to write to file, but also maintain the data in a global variable? (So, our memory footprint might actually be worse now)
b) we delete the file at the end, which would prevent us from being able to re-play the data to `tidal sync...` manually when troubleshooting.

I wonder if we might consider periodically writing to file *and* syncing to tidal tools if some flag is set?

e.g. the below, with no STDOUT writing of JSON:
```./azure_vms.rb -sync-page 10```

as an addiotional option to the existing `./azure_vms.rb | tidal sync ` workflow

2023-10-13 19:09 UTC, gkiranreddy commented
Custom Fields, validated and yes they came through no issues there. 

Regarding writing to the file, I think I literally took the note of writing to the file :)
I understand and it makes sense to write to file and sync at the same time. 

I will try and update the script to take the arg, based on arg batch it, sync to tidal, also write to file. Will delete the files deletion lines.   

Please let me know if any comments.

2023-10-16 09:46 UTC, dcolebatch commented
Sounds great @gkiranreddy

2023-10-18 21:42 UTC, gkiranreddy commented
@dcolebatch updated the script 

- Updates based on the PR review 
- Batching feature as discussed 

we do not need to run the script `./azure_vms.rb | tidal sync servers` anymore. 
Just running the script `./azure_vms.rb` should work. 
```
$ ./azure_vms-working2.rb 
Fetching subscriptions...
=> Found 2 subscriptions.
=> Found 21 resource groups in subscription 4c1a8af4-85cb-44c7-9528-491d3848d341.
=> Found 1 VMs in resource group my-app-Baz6
=> Found 1 VMs in resource group my-app-1ZQb
=> Found 1 VMs in resource group my-app-4Uhb
=> Found 1 VMs in resource group my-app-E4ds
=> Found 1 VMs in resource group my-app-ZeO5
=> Found 1 VMs in resource group my-app-rvSC
=> Found 1 VMs in resource group my-app-2ErM
=> Found 1 VMs in resource group my-app-KkkI
=> Found 1 VMs in resource group my-app-6kFu
=> Found 1 VMs in resource group my-app-wCT4
=> Found 5 resource groups in subscription a6bd8225-08e3-445b-88e4-9279009ddf36.
=> Found 2 VMs in resource group rhel5-demo
Fetching subscriptions...
=> Found 2 subscriptions.
=> Found 21 resource groups in subscription 4c1a8af4-85cb-44c7-9528-491d3848d341.
=> Found 1 App Services in resource group soc-test-db
=> Found 5 resource groups in subscription a6bd8225-08e3-445b-88e4-9279009ddf36.
=> Found 1 App Services in resource group tidal-example-resource-group
Server Sync Successful!
14 entries were created/updated.
Synced 14 of 14 entries to Tidal portal.
Server Sync Successful!
14 entries were created/updated.
```

To run with batches: `./azure_vms-working2.rb -sync-page 5`
```
$ ./azure_vms-working2.rb -sync-page 5
Fetching subscriptions...
=> Found 2 subscriptions.
=> Found 21 resource groups in subscription 4c1a8af4-85cb-44c7-9528-491d3848d341.
=> Found 1 VMs in resource group my-app-Baz6
=> Found 1 VMs in resource group my-app-1ZQb
=> Found 1 VMs in resource group my-app-4Uhb
=> Found 1 VMs in resource group my-app-E4ds
=> Found 1 VMs in resource group my-app-ZeO5
=> Found 1 VMs in resource group my-app-rvSC
=> Found 1 VMs in resource group my-app-2ErM
=> Found 1 VMs in resource group my-app-KkkI
=> Found 1 VMs in resource group my-app-6kFu
=> Found 1 VMs in resource group my-app-wCT4
=> Found 5 resource groups in subscription a6bd8225-08e3-445b-88e4-9279009ddf36.
=> Found 2 VMs in resource group rhel5-demo
Fetching subscriptions...
=> Found 2 subscriptions.
=> Found 21 resource groups in subscription 4c1a8af4-85cb-44c7-9528-491d3848d341.
=> Found 1 App Services in resource group soc-test-db
=> Found 5 resource groups in subscription a6bd8225-08e3-445b-88e4-9279009ddf36.
=> Found 1 App Services in resource group tidal-example-resource-group
Server Sync Successful!
5 entries were created/updated.
Synced 5 of 14 entries to Tidal portal.
Server Sync Successful!
5 entries were created/updated.
Synced 10 of 14 entries to Tidal portal.
Server Sync Successful!
4 entries were created/updated.
Synced 14 of 14 entries to Tidal portal.
Server Sync Successful!
14 entries were created/updated.
```

with `-sync-page` it gives status on the console by incrementing the # `Synced 5 of 14 entries to Tidal portal`

Please review

2023-10-31 02:24 UTC, dcolebatch approved these changes
Really nice changes @gkiranreddy - ready to merge!

2023-10-31 02:24 UTC, merged